/*
 * File: app/view/Gallery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ImageGallery.view.Gallery', {
    extend: 'Ext.Container',
    alias: 'widget.gallery',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Panel'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Gallery',
                layout: {
                    type: 'hbox',
                    pack: 'end'
                },
                items: [
                    {
                        xtype: 'button',
                        name: 'galleryoverlayclose',
                        hidden: true,
                        id: 'galleryoverlayclose',
                        text: 'Close'
                    }
                ]
            },
            {
                xtype: 'panel',
                name: 'gallerypanel',
                plugins: {
                    xclass: 'Ext.plugin.ImageGallery',
                    galleryType: 'listcarousel',
                    //carousel or listcarousel. defaults to carousel
                    autoInitialize: false,
                    // defaults to true. make it false if you want to initialize it later
                    pinchZoom: true,
                    //defaults to true
                    listFullWidth: true,
                    //defaults to false
                    listBorder: '4px solid #fff',
                    //border around the thumb when galleryType is listcarousel
                    defaultClose: false,
                    // defaults to true. if you want to use different button, set false
                    closeButtonId: 'galleryoverlayclose'//ID of the buttion which you want to use to close the modal carousel when defaultClose is false
                },
                data: [
                    'files/slideshow/style1.jpg',
                    'files/slideshow/style2.jpg',
                    'files/slideshow/style3.jpg',
                    'files/slideshow/style4.jpg',
                    'files/slideshow/style5.jpg',
                    'files/slideshow/style6.jpg',
                    'files/slideshow/style7.jpg',
                    'files/slideshow/style8.jpg',
                    'files/slideshow/style9.jpg',
                    'files/slideshow/style10.jpg',
                    'files/slideshow/style11.jpg',
                    'files/slideshow/style12.jpg'
                ]
            }
        ]
    }

});