/*
 * File: app/controller/Gallery.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ImageGallery.controller.Gallery', {
    extend: 'Ext.app.Controller',
    alias: 'controller.gallery',

    config: {
        refs: {
            gallerypanel: 'panel[name=gallerypanel]'
        },

        control: {
            "gallerypanel": {
                activate: 'onPanelActivate'
            }
        }
    },

    onPanelActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        if (!Ext.app.galleryInitialize) {
                    this.galleryinitialize();
                    Ext.app.galleryInitialize = true;
                }
    },

    galleryinitialize: function() {
        this.getGallerypanel().getPlugins()[0].initialize();
    }

});